In [21]:
import pandas as pd
import numpy as np
import yfinance as yf

In [22]:
prices = yf.download(['WMT','NVDA'], start='2020-01-01', end='2026-09-07')['Close']

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_6866/1700523590.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices = yf.download(['WMT','NVDA'], start='2020-01-01', end='2026-09-07')['Close']
[*********************100%***********************]  2 of 2 completed

In [23]:
rets=(prices/prices.shift()-1).dropna()
rets

Ticker          NVDA       WMT
Date
2020-01-03 -0.016006 -0.008828
2020-01-06  0.004194 -0.002036
2020-01-07  0.012107 -0.009265
2020-01-08  0.001876 -0.003432
2020-01-09  0.010983  0.010331
...              ...       ...
2026-08-31  0.014847  0.017267
2026-09-01 -0.015128  0.010012
2026-09-02  0.032055  0.001605
2026-09-03  0.018003  0.021963
2026-09-04  0.008361 -0.011806

[1677 rows x 2 columns]

In [24]:
#Rend esperado
# la diferencia de usar la media o el CAGR es que la media no considera la capitalización de los rendimientos, mientras que el CAGR sí lo hace. Por lo tanto, el CAGR es una medida más precisa del rendimiento real de una inversión a lo largo del tiempo.
# Como te iria en promedio a futuro se usa la media 
rets.mean()*252*100

Ticker
NVDA    68.354180
WMT     19.078702
dtype: float64

In [25]:
#Media Geometrica CAGR

#CAGR<M  el CAGR se utiliza cuanod quieres ver el rendimiento real de una inversión a lo largo del tiempo, 
#considerando la capitalización de los rendimientos. Se calcula utilizando la fórmula:
#CAGR=
(((rets+1).prod())**(1/len(rets))-1)*252*100

Ticker
NVDA    54.966934
WMT     16.309182
dtype: float64

In [26]:
# hay dos tipos de medidas de rendimiento si hoy 7 de sept es hoy , 
# hay medidas de rendimiento que te sirven para el futuro forward looking que te dicen como te iria en promedio a futuro 
# y hay medidas de rendimiento que te dicen como te fue en el pasado backward looking que te dicen como te fue en el pasado.(real)

# el rendimeinto promedio diario es un forward looking y el CAGR es un backward looking.

In [27]:
#Rend Armonico
(len(rets)/((1/(rets+1)).sum())-1)*252*100

Ticker
NVDA    41.602362
WMT     13.531267
dtype: float64

## Rendimiento Esperado

In [28]:
## Rendimiento Esperado
df = pd.DataFrame()
df['Escenario'] = ['Bajista', 'Neutral', 'Alcista']
df['Probabilidad'] = [0.25, 0.30, 0.45]
df['Rendimiento'] = [-10, 5, 20]

df

  Escenario  Probabilidad  Rendimiento
0   Bajista          0.25          -10
1   Neutral          0.30            5
2   Alcista          0.45           20

In [29]:
sum(df['Probabilidad']*df['Rendimiento'])
#al hacer esta operación se obtiene el rendimiento esperado de la inversión, 
# considerando los diferentes escenarios y sus probabilidades asociadas

8.0

In [31]:
E_R=sum(df['Probabilidad']*df['Rendimiento'])
E_V=(df['Probabilidad']*(df['Rendimiento']-E_R)**2).sum()
E_vol=np.sqrt(E_V)

In [33]:
E_R,E_V, E_vol

(8.0, np.float64(148.5), np.float64(12.186057606953941))

# EJERCICIO MEDIDAS PROBABILÍSTICAS II
como analista de deuda en citi, se te ha solicitado estimar la expectativa del mercado respectoa la tasa de interés de la Reserva Federal para el próximo año
Tras revisar los pronósticos de varios analistas en bloomberg, encontraste lo siguiente:

- El mercado asigna un 70% de probabilidad a un escenario dovish, en el que la tasa de interés se situaría en 2%

- Hay un 20% de probabilidad de un escenario neutral, con una tasa del 3%

- Existe un 10% de probabilidad de un escenario hawkish, en el cual la tasa se quedaría en 5.5%

In [34]:
## Rendimiento Esperado
df = pd.DataFrame()
df['Escenario'] = ['Bajista', 'Neutral', 'Alcista']
df['Probabilidad'] = [0.7, 0.2, 0.1]
df['Rendimiento'] = [2, 3, 5.5]

df

  Escenario  Probabilidad  Rendimiento
0   Bajista           0.7          2.0
1   Neutral           0.2          3.0
2   Alcista           0.1          5.5

In [35]:
E_R=sum(df['Probabilidad']*df['Rendimiento'])
E_V=(df['Probabilidad']*(df['Rendimiento']-E_R)**2).sum()
E_vol=np.sqrt(E_V)

In [ ]:
E_R,E_V, E_vol

(2.55, np.float64(1.1225), np.float64(1.0594810050208545))