In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
tickers = ['NVDA', 'WMT']

In [3]:
prices = yf.download(tickers, start='2024-01-01', end='2026-08-26')['Close']
prices

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_53553/1012360723.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices = yf.download(tickers, start='2024-01-01', end='2026-08-26')['Close']
[*********************100%***********************]  2 of 2 completed

Ticker            NVDA         WMT
Date
2024-01-02   48.082535   51.641457
2024-01-03   47.484592   51.644703
2024-01-04   47.912838   51.145432
2024-01-05   49.009876   50.805023
2024-01-08   52.160278   51.304295
...                ...         ...
2026-08-19  217.559998  114.027023
2026-08-20  216.850006  103.591995
2026-08-21  214.720001  103.699997
2026-08-24  208.479996  106.489998
2026-08-25  213.050003  105.379997

[664 rows x 2 columns]

In [4]:
# Calcular los rendimientos
Returns = (prices/prices.shift() - 1).dropna() # Eliminar las filas con valores NaN
Returns

Ticker          NVDA       WMT
Date
2024-01-03 -0.012436  0.000063
2024-01-04  0.009019 -0.009667
2024-01-05  0.022897 -0.006656
2024-01-08  0.064281  0.009827
2024-01-09  0.016975  0.006698
...              ...       ...
2026-08-19 -0.009921 -0.007812
2026-08-20 -0.003263 -0.091514
2026-08-21 -0.009822  0.001043
2026-08-24 -0.029061  0.026905
2026-08-25  0.021921 -0.010424

[663 rows x 2 columns]

In [5]:
# Calcular Valor Esperado (Expected Value)
expected_returns = Returns.mean()  # Asumiendo que los rendimientos son independientes y distribuidos idénticamente
print(expected_returns * 100)  # Convertir a porcentaje

Ticker
NVDA    0.270637
WMT     0.118522
dtype: float64

In [6]:
# Rendmiento del Portafolio
W = np.array([0.5, 0.5])  # Pesos del portafolio (50% NVDA, 50% WMT)
portfolio_return = sum(expected_returns * W) # Calcular el rendimiento del portafolio
print(portfolio_return * 100)  # Convertir a porcentaje

0.19457927186601678

In [7]:
# Riesgo Portafolio
Variance = Returns.var()  # Matriz de covarianza diaria
Covariance = Returns.cov().iloc[0, 1] # Matriz de covarianza anualizada

In [8]:
# Calcular la varianza del portafolio
Varianza_Portafolio = W[0]**2 * Variance[0] + W[1]**2 * Variance[1] + 2 * W[0] * W[1] * Covariance
Desviacion_Portafolio = np.sqrt(Varianza_Portafolio)

print("Varianza del Portafolio:", Varianza_Portafolio)
print("Desviación del Portafolio:", Desviacion_Portafolio)

Varianza del Portafolio: 0.00029210329924833303
Desviación del Portafolio: 0.017091029788995543

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_53553/1331887726.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Varianza_Portafolio = W[0]**2 * Variance[0] + W[1]**2 * Variance[1] + 2 * W[0] * W[1] * Covariance

In [9]:
# Calcular la varianza del portafolio usando la matriz de covarianza
W.T @ Returns.cov() @ W, np.sqrt(W.T @ Returns.cov() @ W) * 100

(np.float64(0.000292103299248333), np.float64(1.709102978899554))

In [10]:
(np.sqrt(W[0] * Variance[0] + W[1] * Variance[1])) * 100

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_53553/1874436709.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  (np.sqrt(W[0] * Variance[0] + W[1] * Variance[1])) * 100

np.float64(2.387079167181877)