In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
tickers = ['KO']

In [3]:
prices = yf.download(tickers, start='2026-01-01', end='2026-08-31')['Close']
prices

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_76781/3592228844.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices = yf.download(tickers, start='2026-01-01', end='2026-08-31')['Close']
[*********************100%***********************]  1 of 1 completed

Ticker             KO
Date
2026-01-02  68.207611
2026-01-05  67.043182
2026-01-06  66.944504
2026-01-07  66.648460
2026-01-08  68.454308
...               ...
2026-08-24  91.989998
2026-08-25  91.639999
2026-08-26  90.080002
2026-08-27  89.059998
2026-08-28  89.660004

[165 rows x 1 columns]

In [4]:
# Calcular los rendimientos
rets = (prices/prices.shift() - 1).dropna() # Eliminar las filas con valores NaN
rets

Ticker            KO
Date
2026-01-05 -0.017072
2026-01-06 -0.001472
2026-01-07 -0.004422
2026-01-08  0.027095
2026-01-09  0.016434
...              ...
2026-08-24  0.009769
2026-08-25 -0.003805
2026-08-26 -0.017023
2026-08-27 -0.011323
2026-08-28  0.006737

[164 rows x 1 columns]

In [5]:
#Rendimiento esperado de cada activo
mu=rets.mean()

In [6]:
#Rendimiento Portafolio
w=np.array([0.2, 0.2, 0.2, 0.2, 0.2])  # Pesos del portafolio (20% cada activo)
R_port=sum(w*mu)
R_port*100*252

ValueError: Length of values (5) does not match length of index (1)

In [ ]:
#Riesgo de un portafolio
cov=rets.cov()
vol_port=np.sqrt(w.T @ cov @ w)
vol_port*100*np.sqrt(252)

np.float64(21.474652836724697)

In [ ]:
cov
#no podemos interpretar estos 0 porque la magnitud 
# va a tomar el valor abosluto y los va a sumar

Ticker      AAPL      AMZN      MSFT      NVDA       WMT
Ticker
AAPL    0.000305  0.000130  0.000099  0.000159  0.000062
AMZN    0.000130  0.000423  0.000185  0.000276  0.000046
MSFT    0.000099  0.000185  0.000287  0.000219  0.000019
NVDA    0.000159  0.000276  0.000219  0.000922  0.000014
WMT     0.000062  0.000046  0.000019  0.000014  0.000218

In [ ]:
rets.corr()

Ticker      AAPL      AMZN      MSFT      NVDA       WMT
Ticker
AAPL    1.000000  0.361332  0.334405  0.299800  0.241137
AMZN    0.361332  1.000000  0.532321  0.442677  0.150536
MSFT    0.334405  0.532321  1.000000  0.426770  0.076781
NVDA    0.299800  0.442677  0.426770  1.000000  0.032101
WMT     0.241137  0.150536  0.076781  0.032101  1.000000

In [ ]:
#Correlación es baja cuando esta entre-.25 y +.25
#Cuadrada es decir de nxn activos
#Y es una matriz simétrica,