In [43]:
import pandas as pd
import numpy as np
import yfinance as yf

In [44]:
tickers=['NVDA','WMT']

In [45]:
prices = yf.download(tickers, start='2024-01-01', end='2026-08-26')['Close']
prices

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_74329/1012360723.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices = yf.download(tickers, start='2024-01-01', end='2026-08-26')['Close']
[*********************100%***********************]  2 of 2 completed

Ticker            NVDA         WMT
Date
2024-01-02   48.082527   51.641464
2024-01-03   47.484592   51.644707
2024-01-04   47.912838   51.145435
2024-01-05   49.009884   50.805027
2024-01-08   52.160290   51.304291
...                ...         ...
2026-08-19  217.559998  114.027023
2026-08-20  216.850006  103.591995
2026-08-21  214.720001  103.699997
2026-08-24  208.479996  106.489998
2026-08-25  213.050003  105.379997

[664 rows x 2 columns]

In [46]:
#rend diarios
rets=(prices/prices.shift()-1).dropna()
rets

Ticker          NVDA       WMT
Date
2024-01-03 -0.012436  0.000063
2024-01-04  0.009019 -0.009667
2024-01-05  0.022897 -0.006656
2024-01-08  0.064281  0.009827
2024-01-09  0.016975  0.006698
...              ...       ...
2026-08-19 -0.009921 -0.007812
2026-08-20 -0.003263 -0.091514
2026-08-21 -0.009822  0.001043
2026-08-24 -0.029061  0.026905
2026-08-25  0.021921 -0.010424

[663 rows x 2 columns]

In [47]:
#Rend promedio (Valor Esperado- Rendimiento Esperado)
mu=rets.mean()*252
mu*100

Ticker
NVDA    68.200424
WMT     29.867532
dtype: float64

In [48]:
#Rendimiento del Portafolio
w_port=np.array([0.5,0.5])

r_port=sum(w_port*mu)
r_port

#es la suma ponderada del peso que tiene el activo en el portafolio por su rendimiento

0.4903397768626286

1. La covarianza mide la relacion lineal entre dos activos.   
2. No puede interpretar el valor o magnitud solo la dirección.    
3. La covarianza esta entre - infinito -- + infinito
4. Covarianza positiva me dice que la relación entre el activo x y y es positiva.   (si uno sube el otro tmb sube pero no se sabe cto)
5. Covarianza 0 indica que no hay relación lineal.   
6. Covarianza <0 la relación es negativa

In [49]:
#Riesgo portafolio
variance=rets.var()

In [50]:
cov=rets.cov()

In [51]:
varianza_port=w_port[0]**2*variance[0]+2*w_port[0]*w_port[1]*cov.iloc[0,1]+w_port[1]**2*variance[1]
desvest_port=np.sqrt(varianza_port)
varianza_port,desvest_port

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_74329/2083540358.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  varianza_port=w_port[0]**2*variance[0]+2*w_port[0]*w_port[1]*cov.iloc[0,1]+w_port[1]**2*variance[1]

(np.float64(0.00029210352547575166), np.float64(0.017091036407302855))

In [ ]:
np.sqrt(w_port[0]*variance[0])

In [56]:
w_port.T @ cov @ w_port,np.sqrt(w_port.T @ cov @ w_port)

(np.float64(0.0002921035254757516), np.float64(0.01709103640730285))

In [ ]:
# "*" Multiplicación escalar
# "@" Multiplicación matricial