Asume que eres el Portfolio Manager de Banamex y deseas comparar el desempeño de una estrategia de inversión activa con una pasiva (Benchmark), realizando un análisis básico del riesgo y rendimiento de ambas estrategias. Sigue los pasos para evaluarlas:

1.- Tu estrategia de inversión activa contiene las sigtes. acciones con ponderaciones equitativas JP Morgan Chase, Visa, Goldman Sachs Group Inc, Progressive Corp, para tu portafolio:

Descarga los precios de cierre ajustado desde el 2018-01-01 hasta el 2026-09-07 .
Calcula las métricas de riesgo y rendimiento anuales, coeficiente de variación, ratio de Sharpe y la matriz de correlación. (20%)
Interpreta la matriz de correlación. (10%)
 

2.- Ahora, compara tu estrategia de inversión activa contra una pasiva:

En base a tus acciones y su sector del GICS busca un índice que represente el sector de tus activos, comenta el nombre, ticker y los constituyentes de este. Descarga los precios del índice Yahoo Finance. (10%)
Para el índice, calcula las métricas de riesgo y rendimiento anuales, además del ratio de Sharpe. (20%)
 

3. -A manera de conclusión, en función de las métricas calculadas y en base a los dos Radios de Sharpe calculados para cada estrategia, responde:

¿En que estrategia invertirías y por qué?, ¿Habría una forma de mejorar la estrategia activa? es decir, ¿Qué podrías cambiar en tu portafolio para obtener mejores resultados? (20%)
Calcula el rendimiento geométrico y armónico para la estrategia pasiva y activa, discute en que casos sería conveniente utilizar uno u otro (20%)
Nota: Asume una tasa libre de riesgo del 4% anual.
Entrega tu tarea en un html descargado de Jupyter Notebook.

In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

In [2]:
tickers=['JPM','V','GS','PGR','^SP500-40']
prices=yf.download(tickers,start='2018-01-01',end='2026-09-07')['Close']
rets=(prices/prices.shift()-1).dropna()
rets

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_78550/47458559.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices=yf.download(tickers,start='2018-01-01',end='2026-09-07')['Close']
[*********************100%***********************]  5 of 5 completed

Ticker            GS       JPM       PGR         V  ^SP500-40
Date
2018-01-03 -0.009309  0.001019 -0.000542  0.009955   0.005349
2018-01-04  0.013976  0.014325 -0.000181  0.003718   0.009375
2018-01-05 -0.005101 -0.006420  0.003796  0.023949   0.002997
2018-01-08 -0.014520  0.001477  0.003062  0.004038  -0.001250
2018-01-09  0.008459  0.005069  0.008438 -0.001927   0.007129
...              ...       ...       ...       ...        ...
2026-07-13 -0.008785 -0.005766  0.016297  0.025160   0.006085
2026-07-14  0.089960  0.024990 -0.033692 -0.004836   0.002081
2026-07-15  0.010588  0.011724 -0.094271 -0.002472   0.006571
2026-07-16 -0.049138 -0.010839  0.002826  0.028158   0.004051
2026-07-17 -0.027605 -0.005974  0.010447 -0.018021  -0.009065

[2141 rows x 5 columns]

## ESTRATEGIA ACTIVA

In [3]:
retsA=rets.drop(['^SP500-40'],axis=1)
w_portA=np.array([.25,.25,.25,.25])
cov=retsA.cov()

In [4]:
daily_retsA=retsA.mean()
mu=daily_retsA*252

daily_varianceA=w_portA.T@cov@w_portA
annual_varianceA=daily_varianceA*252
E_R_portA=sum(mu*w_portA)
E_R_portA*100

20.65095529985397

In [5]:
daily_volatilityA=np.sqrt(daily_varianceA)
annual_volatilityA=np.sqrt(annual_varianceA)

annual_volatilityA*100

np.float64(22.4262956939284)

In [6]:
Sharpe_RatioA= E_R_portA/annual_volatilityA
Sharpe_RatioA

np.float64(0.9208366634283218)

In [7]:
cv= annual_volatilityA/E_R_portA
cv

np.float64(1.0859689233885943)

In [8]:
corr=retsA.corr()
corr

Ticker        GS       JPM       PGR         V
Ticker
GS      1.000000  0.807171  0.317536  0.543555
JPM     0.807171  1.000000  0.398922  0.583161
PGR     0.317536  0.398922  1.000000  0.412345
V       0.543555  0.583161  0.412345  1.000000

In [19]:
geometric_return=(((E_R_portA+1).prod())**(1/len(E_R_portA))-1)*252
geometric_return

AttributeError: 'float' object has no attribute 'prod'

## ESTRATEGIA PASIVA

In [10]:
retsP=rets[['^SP500-40']]
rf=.04

In [11]:
daily_retsP=retsP.mean()
muP=daily_retsP*252
muP*100

Ticker
^SP500-40    10.777523
dtype: float64

In [12]:
daily_varianceP=retsP.var()
annual_varianceP=daily_varianceP*252

In [13]:
daily_volatilityP=np.sqrt(daily_varianceP)
annual_volatilityP=np.sqrt(annual_varianceP)
annual_volatilityP*100

Ticker
^SP500-40    23.361256
dtype: float64

In [14]:
Sharpe_RatioP= (muP-rf)/annual_volatilityP
Sharpe_RatioP

Ticker
^SP500-40    0.290118
dtype: float64

In [15]:
cvP= muP/annual_volatilityP
cvP

Ticker
^SP500-40    0.461342
dtype: float64