# Tarea 2 - Portafolio de Inversión

**Integrantes:**  
María Fernanda Gómez Flores  
Carlos Hasan Hernández Rohan

**Periodo de análisis:** 01/01/2020 - 31/08/2026

In [1]:
#importar librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

## Selección de activos

Para formar el portafolio se seleccionaron cuatro activos buscando que pertenezcan a mercados o tipos de exposición diferentes, con el objetivo de reducir la correlación entre ellos y mejorar la diversificación.

Los activos seleccionados tendrán una ponderación igual dentro del portafolio.

In [2]:
#Definir activos
tickers=['SPY', 'GLD', 'DBA', 'UUP']

In [3]:
#descargar datos
prices=yf.download(tickers,start='2020-01-01',end='2026-09-01')["Close"]
prices

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_83322/60511789.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices=yf.download(tickers,start='2020-01-01',end='2026-09-01')["Close"]
[*********************100%***********************]  4 of 4 completed

Ticker            DBA         GLD         SPY        UUP
Date
2020-01-02  14.560220  143.949997  296.125305  22.466347
2020-01-03  14.392557  145.860001  293.882996  22.492212
2020-01-06  14.427855  147.389999  295.004089  22.440485
2020-01-07  14.463152  147.970001  294.174713  22.518076
2020-01-08  14.392557  146.860001  295.742432  22.578421
...               ...         ...         ...        ...
2026-08-25  28.280001  428.070007  765.909973  27.940001
2026-08-26  28.590000  421.320007  766.080017  28.020000
2026-08-27  28.820000  422.600006  771.099976  28.020000
2026-08-28  29.190001  408.890015  769.349976  28.180000
2026-08-31  29.320000  408.420013  767.049988  28.120001

[1674 rows x 4 columns]

In [4]:
#rend diarios
rets=(prices/prices.shift()-1).dropna()
rets

Ticker           DBA       GLD       SPY       UUP
Date
2020-01-03 -0.011515  0.013269 -0.007572  0.001151
2020-01-06  0.002452  0.010490  0.003815 -0.002300
2020-01-07  0.002446  0.003935 -0.002811  0.003458
2020-01-08 -0.004881 -0.007502  0.005329  0.002680
2020-01-09  0.002452 -0.005652  0.006781  0.001909
...              ...       ...       ...       ...
2026-08-25 -0.000707  0.003234  0.003196 -0.000715
2026-08-26  0.010962 -0.015768  0.000222  0.002863
2026-08-27  0.008045  0.003038  0.006553  0.000000
2026-08-28  0.012838 -0.032442 -0.002269  0.005710
2026-08-31  0.004454 -0.001149 -0.002990 -0.002129

[1673 rows x 4 columns]

In [5]:
#rend promedio
mu=rets.mean()*252
mu*100

Ticker
DBA    11.541008
GLD    17.424484
SPY    16.372998
UUP     3.650571
dtype: float64

In [ ]:
#Rendimiento del Portafolio
w_port=np.array([0.25,0.25,0.25,0.25])

r_port=sum(w_port*mu)
r_port

#es la suma ponderada del peso que tiene el activo en el portafolio por su rendimiento

0.12247265209328403