In [50]:
#importar librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

In [51]:
#Definir activos
tickers=['SPY', 'GLD', 'DBA', 'BTC-USD']

In [52]:
#descargar datos
prices=yf.download(tickers,start='2020-01-01',end='2026-09-01')["Close"]
prices

/var/folders/x9/60hcc2ln62d3r3xyv90d3wl40000gn/T/ipykernel_81007/1011438398.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices=yf.download(tickers,start='2020-01-01',end='2026-09-01')["Close"]
[*********************100%***********************]  4 of 4 completed

Ticker           BTC-USD        DBA         GLD         SPY
Date
2020-01-01   7200.174316        NaN         NaN         NaN
2020-01-02   6985.470215  14.560221  143.949997  296.125275
2020-01-03   7344.884277  14.392556  145.860001  293.882965
2020-01-04   7410.656738        NaN         NaN         NaN
2020-01-05   7411.317383        NaN         NaN         NaN
...                  ...        ...         ...         ...
2026-08-27  80257.539062  28.820000  422.600006  771.099976
2026-08-28  77830.289062  29.190001  408.890015  769.349976
2026-08-29  78245.812500        NaN         NaN         NaN
2026-08-30  77667.570312        NaN         NaN         NaN
2026-08-31  78548.632812  29.320000  408.420013  767.049988

[2435 rows x 4 columns]

In [53]:
#rend diarios
rets=(prices/prices.shift()-1).dropna()
rets

Ticker       BTC-USD       DBA       GLD       SPY
Date
2020-01-03  0.051452 -0.011515  0.013269 -0.007572
2020-01-07  0.050774  0.002446  0.003935 -0.002812
2020-01-08 -0.010269 -0.004881 -0.007502  0.005330
2020-01-09 -0.024851  0.002453 -0.005652  0.006780
2020-01-10  0.036487  0.009174  0.006026 -0.002878
...              ...       ...       ...       ...
2026-08-21  0.072603 -0.002114  0.019506  0.004091
2026-08-25 -0.005059 -0.000707  0.003234  0.003196
2026-08-26  0.005886  0.010962 -0.015768  0.000222
2026-08-27  0.015566  0.008045  0.003038  0.006553
2026-08-28 -0.030243  0.012838 -0.032442 -0.002269

[1310 rows x 4 columns]

In [54]:
#Rend promedio (Valor Esperado- Rendimiento Esperado)
mu=rets.mean()*252
mu*100

Ticker
BTC-USD    39.876672
DBA        12.698697
GLD        15.699948
SPY        15.120233
dtype: float64

In [56]:
#Rendimiento del Portafolio
w_port=np.array([0.25,0.25,0.25,0.25])

r_port=sum(w_port*mu)
r_port

#es la suma ponderada del peso que tiene el activo en el portafolio por su rendimiento

0.20848887829150797

In [57]:
#Riesgo portafolio
variance=rets.var()

In [58]:
cov=rets.cov()

In [59]:
w_port.T @ cov @ w_port,np.sqrt(w_port.T @ cov @ w_port)

(np.float64(0.00013758767108364297), np.float64(0.011729777111422151))